version: "3"

services:
    postgres:
        image: postgres:15.2-alpine
        environment:
            - POSTGRES_DB=online_stores
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5434:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        networks:
        - app-tier

    server:
        build:
            context: .
        image:
            online-store:latest
        depends_on:
        - postgres
        ports:
        - "3000:3000"
        networks:
        - app-tier


volumes:
    pgdata:

networks:
  app-tier:
    driver: bridge