version: "3"

services:
    postgres:
        image: postgres:15.2-alpine
        environment:
            - POSTGRES_DB=online_stores
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        networks:
        - app-tier

    server:
        build:
            context: .
        image:
            online-store:latest
        ports:
            - "3000:3000"
        volumes:
            - api:/usr/src/app/
        depends_on:
            - postgres
        networks:
            - app-tier


volumes:
    api:
    pgdata:

networks:
  app-tier:
    driver: bridge